homeSuccess:
  customize:
    communityTopicList:
      template: [communityTopic, communityTopicList]
      parts:    [communityMember]
      target:   [after]
      is_component: true

    communityEventList:
      template: [communityEvent, communityEventList]
      parts:    [communityMember]
      target:   [after]
      is_component: true
