homeSuccess:
  customize:
    communityTopicList:
      template: [communityTopic, communityTopicList]
      parts: [communityHome]
      target: [lastRow]
      is_component: true

    communityEventList:
      template: [communityEvent, communityEventList]
      parts: [communityHome]
      target: [lastRow]
      is_component: true

    searchFormLine:
      template: [communityTopic, searchFormLine]
      parts: [communityHome]
      target: [after]
      is_component: false

searchSuccess:
  customize:
    topicSearchLink:
      template: [communityTopic, topicSearchLink]
      parts:    [searchCommunity]
      target:   [after]
      is_component: false
