homeSuccess:
  customize:
    test:
      template: [community_topic, test]
      parts: [communityHome]
      target: [lastRaw]
editSuccess:
  customize:
    privilege:
      template: [community_topic, privilege]
      parts: [formCommunity]
      target: [lastRaw]
