homeSuccess:
  customize:
    communityTopicList:
      template: [communityTopic, communityTopicList]
      parts: [communityHome]
      target: [lastRow]
      is_component: true

    communityEventList:
      template: [communityEvent, communityEventList]
      parts: [communityHome]
      target: [lastRow]
      is_component: true
