propel:
  _attributes: { package: plugins.opCommunityTopicPlugin.lib.model }

  community_topic:
    id: ~
    community_id: { type: integer, required: true, foreignTable: community, foreignReference: id }
    member_id: { type: integer, required: true, foreignTable: member, foreignReference: id }
    name: { type: longvarchar, required: true }
    body: { type: longvarchar, required: true }
    created_at: ~
    updated_at: ~

  community_topic_comment:
    id: ~
    community_topic_id: { type: integer, required: true, foreignTable: community_topic, foreignReference: id }
    member_id: { type: integer, required: true, foreignTable: member, foreignReference: id }
    body: { type: longvarchar, required: true }
    created_at: ~
    updated_at: ~
