propel:
  _attributes: { package: plugins.opCommunityTopicPlugin.lib.model }

  community_topic:
    id: ~
    community_id: { type: integer, required: true, foreignTable: community, foreignReference: id, onDelete: cascade }
    member_id: { type: integer, foreignTable: member, foreignReference: id, onDelete: setnull }
    name: { type: longvarchar, required: true }
    body: { type: longvarchar, required: true }
    created_at: ~
    updated_at: ~
    topic_updated_at: { type: timestamp }

  community_topic_comment:
    id: ~
    community_topic_id: { type: integer, required: true, foreignTable: community_topic, foreignReference: id, onDelete: cascade }
    member_id: { type: integer, foreignTable: member, foreignReference: id, onDelete: setnull }
    number: { type: integer, required: true, default: 0 }
    body: { type: longvarchar, required: true }
    created_at: ~

  community_event:
    id: ~
    community_id: { type: integer, required: true, foreignTable: community, foreignReference: id, onDelete: cascade }
    member_id: { type: integer, foreignTable: member, foreignReference: id, onDelete: setnull }
    name: { type: longvarchar, required: true }
    body: { type: longvarchar, required: true }
    created_at: ~
    updated_at: ~
    event_updated_at: { type: timestamp }
    open_date: { type: timestamp }
    open_date_comment: { type: longvarchar }
    area: { type: longvarchar }
    application_deadline: { type: timestamp }
    capacity: { type: integer }

  community_event_comment:
    id: ~
    community_event_id: { type: integer, required: true, foreignTable: community_event, foreignReference: id, onDelete: cascade }
    member_id: { type: integer, foreignTable: member, foreignReference: id, onDelete: setnull }
    number: { type: integer, required: true, default: 0 }
    body: { type: longvarchar, required: true }
    created_at: ~
